### ISSUE TITLE
Cannot run the example script from the tutorial on WSL - Ubuntu

### ISSUE THREAD

**Issue by anywaylupin** [Vikit-ai/sdk#202]
### **Issue Description**
Cannot run the example script from the tutorial on WSL - Ubuntu

---

### **Error Log**
2025-02-08 22:38:24.090 | ERROR    | vikit.common.context_managers:__exit__:78 - Exception handled, with details: Cannot connect to host replicate.delivery:443 ssl:default [Connect call failed ('127.0.0.1', 443)] and trace <traceback object at 0x7ff391a9f040>

![Image](https://github.com/user-attachments/assets/418d01fe-193c-491b-a84e-34592e658d39)

**Comment by nwettstein** [comment]
Hi @anywaylupin, thank you for reporting this issue. We have an idea of what the problem might be and are working on a potential fix.

**Comment by leclem** [comment]
Hello,

The issue was due to the fact that the dowload_or_copy function did not retry properly with exponential backoff in case the file was not yet available in the backend. We fixed it through PR [fd114ebd82f9244e51573ba33f9eb4c958e5179f](https://github.com/Vikit-ai/sdk/commit/fd114ebd82f9244e51573ba33f9eb4c958e5179f)
Could you retry and see if it works now ? 

Clément

**Comment by anywaylupin** [comment]
Hi team, I retried with the provided PR but the issue remained

**Comment by anywaylupin** [comment]
Here is the script I used (the script is from the Website)

```
import asyncio
from vikit.common.context_managers import WorkingFolderContext
from vikit.music_building_context import MusicBuildingContext
from vikit.prompt.prompt_factory import PromptFactory
from vikit.video.prompt_based_video import PromptBasedVideo
from vikit.video.video_build_settings import VideoBuildSettings

prompt_text = "A flock of birds takes flight, soaring gracefully over a vast, rolling landscape as the sun sets in the distance."

video_build_settings = VideoBuildSettings(
    music_building_context=MusicBuildingContext(
        apply_background_music=True,
        generate_background_music=True,
    ),
    include_read_aloud_prompt=True,
    output_video_file_name="video.mp4",
)


async def create_video():
    prompt = await PromptFactory().create_prompt_from_text(prompt_text)
    video = PromptBasedVideo(prompt=prompt)
    await video.build(build_settings=video_build_settings)


if __name__ == "__main__":
    with WorkingFolderContext("output_folder"):
        asyncio.run(create_video())
```

**Comment by nwettstein** [comment]
Hi @anywaylupin,
sorry to hear that the issue is not resolved. I have a few follow up questions if you don't mind helping us out a bit more:

1. On your second attempt containing the fix, did you get similar-looking log output? Specifically, did you again get repeated lines like `Checking path: https://replicate.delivery/yhqm/...` ? Could you again share the last 10-20 log lines before the error occurs please?

2. I just tried to run the script from Australia without issues, so I wonder if maybe there's a problem with accessing replicate.delivery from where you are. Could you run the following command in a terminal and share the result with us please?

    `ping replicate.delivery`
